api_version = "2023-10"

[[extensions]]
type = "theme_app_extension"
name = "Pre-order Button"

[extensions.settings]
[[extensions.settings.blocks]]
type = "preorder_button"
name = "Pre-order Button"
target = "section_group://product-information"

[[extensions.settings.blocks.settings]]
type = "text"
id = "button_text"
label = "Button Text"
default = "Pre-order Now"

[[extensions.settings.blocks.settings]]
type = "color"
id = "button_color"
label = "Button Color"
default = "#007ace"

[[extensions.settings.blocks.settings]]
type = "checkbox"
id = "show_message"
label = "Show Pre-order Message"
default = true

